org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2,TLSv1.3
android.useAndroidX=true
systemProp.https.proxyHost=
systemProp.https.proxyPort=
cmake.dir=C\:\\Users\\xingan\\AppData\\Local\\Android\\Sdk\\cmake\\4.1.2
